version: "3"

includes:
  lint: "task-lint.yml"
  # utils: "tools/yscope-dev-utils/taskfiles/utils.yml"

vars:
  G_BUILD_BASE_DIR: "{{.TASKFILE_DIR}}/build"
  G_BUILD_TYPE: "Release"
  G_BUILD_DIR: "{{.G_BUILD_BASE_DIR}}/{{.G_BUILD_TYPE}}"
  G_DEPS_DIR: "{{.G_BUILD_BASE_DIR}}/deps"
  G_INSTALL_PREFIX: "{{.TASKFILE_DIR}}"
  G_INSTALL_INCLUDE_DIR: "{{.G_INSTALL_PREFIX}}/include/ffi_go"
  G_INSTALL_LIB: '{{printf "%s/lib/libclp_ffi_%s_%s.a" .G_INSTALL_PREFIX OS ARCH}}'
  G_INSTALL_CHECKSUM_FILE: "{{.G_BUILD_BASE_DIR}}/install.md5"

tasks:
  default:
    cmds:
      - task: "build"

  build-cpp:
    deps:
      - "install-deps-cpp-clp"
      - "install-deps-cpp-outcome"
      - "install-deps-cpp-msgpack"
    cmds:
      - task: "cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          SOURCE_DIR: "{{.TASKFILE_DIR}}/cpp"
          CMAKE_ARGS: >-
            -DCMAKE_BUILD_TYPE="{{.G_BUILD_TYPE}}"
            -DOS_SUFFIX="{{OS}}"
            -DARCH_SUFFIX="{{ARCH}}"
            -DDEPS_DIR="{{.G_DEPS_DIR}}"
            -Dmsgpack-cxx_ROOT="{{.G_DEPS_DIR}}/msgpack-install"
            -Doutcome_SOURCE_DIR="{{.G_DEPS_DIR}}/outcome-src"

  build-go:
    aliases: ["build"]
    deps:
      - "build-go-generate"
      - "install-cpp"
    sources:
      - "{{.TASKFILE_DIR}}/go.mod"
      - "{{.TASKFILE_DIR}}/ffi/**/*"
      - "{{.TASKFILE_DIR}}/ir/**/*"
    cmds:
      - "go build {{.TASKFILE_DIR}}/..."

  build-go-generate:
    sources:
      - "{{.TASKFILE_DIR}}/go.mod"
      - "{{.TASKFILE_DIR}}/ffi/**/*"
      - "{{.TASKFILE_DIR}}/ir/**/*"
      - exclude: "{{.TASKFILE_DIR}}/ir/irerror_string.go"
    generates: ["{{.TASKFILE_DIR}}/ir/irerror_string.go"]
    cmds:
      - |-
        go install "golang.org/x/tools/cmd/stringer@latest"
        go generate "{{.TASKFILE_DIR}}/..."

  install-cpp:
    deps: ["build-cpp"]
    cmds:
      - task: "cmake-install"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          DATA_PATHS:
            - "{{.G_INSTALL_INCLUDE_DIR}}"
            - "{{.G_INSTALL_LIB}}"
          INSTALL_PREFIX: "{{.G_INSTALL_PREFIX}}"
          CHECKSUM_FILE: "{{.G_INSTALL_CHECKSUM_FILE}}"

  install-deps-cpp-clp:
    vars:
      SOURCE_DIR: '{{default (printf "%s/clp-src/clp" .G_DEPS_DIR) .SOURCE_DIR}}'
    deps: ["install-deps-cpp-clp-json"]
    cmds:
      - task: "fetch_src"
        vars:
          OUTPUT_DIR: "{{.SOURCE_DIR}}"
          URL: "https://github.com/y-scope/clp/archive/e21672b906641c4724a25ea74f13857afdebe0e8.tar.gz"
          URL_SHA256: "b7ab19af62fb0601d858047452e2f330489070caccd4aaf1e09709f6ca6324ab"

  install-deps-cpp-clp-json:
    cmds:
      - task: "curl"
        vars:
          OUTPUT_FILE: "{{.G_DEPS_DIR}}/json-src/json/single_include/nlohmann/json.hpp"
          URL: "https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp"
          URL_SHA256: "9bea4c8066ef4a1c206b2be5a36302f8926f7fdc6087af5d20b417d0cf103ea6"

  install-deps-cpp-msgpack:
    vars:
      BUILD_DIR: '{{default (printf "%s/msgpack-build" .G_DEPS_DIR) .BUILD_DIR}}'
      SOURCE_DIR: '{{default (printf "%s/msgpack-src" .G_DEPS_DIR) .SOURCE_DIR}}'
      INSTALL_PREFIX: '{{default (printf "%s/msgpack-install" .G_DEPS_DIR) .INSTALL_PREFIX}}'
    cmds:
      - task: "fetch_src"
        vars:
          OUTPUT_DIR: "{{.SOURCE_DIR}}"
          URL: "https://github.com/msgpack/msgpack-c/archive/cpp-6.1.0.tar.gz"
          URL_SHA256: "5e63e4d9b12ab528fccf197f7e6908031039b1fc89cd8da0e97fbcbf5a6c6d3a"
      - task: "cmake-build"
        vars:
          BUILD_DIR: "{{.BUILD_DIR}}"
          SOURCE_DIR: "{{.SOURCE_DIR}}"
          CMAKE_ARGS: >-
            -DMSGPACK_CXX20="ON"
            -DMSGPACK_USE_BOOST="OFF"
      - task: "cmake-install"
        vars:
          BUILD_DIR: "{{.BUILD_DIR}}"
          INSTALL_PREFIX: "{{.INSTALL_PREFIX}}"

  install-deps-cpp-outcome:
    vars:
      SOURCE_DIR: '{{default (printf "%s/outcome-src/outcome/single-header" .G_DEPS_DIR) .SOURCE_DIR}}'
    cmds:
      - task: "curl"
        vars:
          OUTPUT_FILE: "{{.SOURCE_DIR}}/outcome.hpp"
          URL: "https://github.com/ned14/outcome/raw/v2.2.10/single-header/outcome.hpp"
          URL_SHA256: "ad624622dcb1613027d39bd1aac93a13f11f46df197aa494a3980bef3c044dad"

  clean:
    cmds:
      - |-
        rm -fr "{{.G_INSTALL_INCLUDE_DIR}}"
        rm -f "{{.G_INSTALL_LIB}}"
        rm -fr "{{.G_BUILD_DIR}}"
        rm -f "{{.G_BUILD_DIR}}.md5"
        go clean -cache

  clean-all:
    deps:
      - "clean-deps"
      - "clean"
    cmds:
      - "rm -fr {{.G_BUILD_DIR}}"

  clean-deps:
    cmds:
      - "rm -fr {{.G_DEPS_DIR}}"

  test-all:
    deps:
      - "test"
      - "test-bazel"

  test:
    deps: ["build-go"]

  build-bazel:
    cmds:
      - "bazel build //..."

  clean-bazel:
    cmds:
      - "bazel clean --expunge"

  test-bazel:
    cmds:
      - "bazel test //ir:ir_test"


## MOVE TO UTILS


  cmake-build:
    label: "cmake-build: {{.SOURCE_DIR}} {{.BUILD_DIR}}"
    internal: true
    vars:
      CHECKSUM_FILE: '{{default (printf "%s.md5" .BUILD_DIR) .CHECKSUM_FILE}}'
      CMAKE_ARGS: "{{default nil .CMAKE_ARGS}}"
    requires:
      vars: ["BUILD_DIR", "SOURCE_DIR"]
    sources:
      - "{{.SOURCE_DIR}}/**/*"
      - exclude: "{{.SOURCE_DIR}}/.cache/**/*"
      - exclude: "{{.SOURCE_DIR}}/compile_commands.json"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_PATHS: ["{{.BUILD_DIR}}"]
          EXCLUDE_PATHS: ["install_manifest.txt"]
    cmds:
      # TODO: remove debugging
      - for: sources
        cmd: echo "{{.ITEM}}"
      - stat "{{.CHECKSUM_FILE}}" || true
      - >-
        cmake
        -S "{{.SOURCE_DIR}}"
        -B "{{.BUILD_DIR}}"
        {{.CMAKE_ARGS}}
      - >-
        cmake
        --build "{{.BUILD_DIR}}"
        --parallel
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_PATHS: ["{{.BUILD_DIR}}"]
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
          EXCLUDE_PATHS: ["install_manifest.txt"]

  cmake-install:
    label: "cmake-install: {{.BUILD_DIR}} {{.INSTALL_PREFIX}}"
    internal: true
    vars:
      CHECKSUM_FILE: '{{default (printf "%s.md5" .INSTALL_PREFIX) .CHECKSUM_FILE}}'
      _INSTALL_PREFIX_ARRAY: ["{{.INSTALL_PREFIX}}"]
      DATA_PATHS:
        ref: "default ._INSTALL_PREFIX_ARRAY .DATA_PATHS"
    requires:
      vars: ["BUILD_DIR", "INSTALL_PREFIX"]
    sources:
      - "{{.BUILD_DIR}}/**/*"
      - exclude: "{{.BUILD_DIR}}/install_manifest.txt"
    generates: ["{{.CHECKSUM_FILE}}"]
    deps:
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_PATHS:
            ref: ".DATA_PATHS"
    cmds:
      # TODO: remove debugging
      - for: sources
        cmd: echo "{{.ITEM}}"
      - stat "{{.CHECKSUM_FILE}}" || true
      - >-
        cmake
        --install "{{.BUILD_DIR}}"
        --prefix "{{.INSTALL_PREFIX}}"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_PATHS:
            ref: ".DATA_PATHS"
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"

  curl:
    label: "curl: {{.OUTPUT_FILE}}"
    internal: true
    vars:
      OUTPUT_FILE: "{{default (base .URL) .OUTPUT_FILE}}"
    requires:
      vars: ["URL", "URL_SHA256"]
    generates:
      - "{{.OUTPUT_FILE}}"
    status:
      - >-
        diff
        <(echo "{{.URL_SHA256}}")
        <(openssl dgst -sha256 "{{.OUTPUT_FILE}}"
        | awk '{print $2}')
    cmds:
      - |-
        mkdir -p "{{dir .OUTPUT_FILE}}"
        curl -L "{{.URL}}" -o "{{.OUTPUT_FILE}}"

  # @param {string} OUTPUT_DIR
  # @param {string} URL
  # @param {string} URL_SHA256
  fetch_src:
    label: "fetch_src: {{.OUTPUT_DIR}}"
    internal: true
    vars:
      CHECKSUM_FILE: '{{default (printf "%s.md5" .OUTPUT_DIR) .CHECKSUM_FILE}}'
      STRIP: "{{default 1 .STRIP}}"
      TAR_FILE: '{{default (printf "%s.tar.gz" .OUTPUT_DIR) .TAR_FILE}}'
    requires:
      vars: ["OUTPUT_DIR", "URL", "URL_SHA256"]
    sources: ["{{.TASKFILE}}"]
    generates: ["{{.CHECKSUM_FILE}}", "{{.TAR_FILE}}"]
    deps:
      - task: "curl"
        vars:
          URL: "{{.URL}}"
          URL_SHA256: "{{.URL_SHA256}}"
          OUTPUT_FILE: "{{.TAR_FILE}}"
      - task: "utils:validate-checksum"
        vars:
          CHECKSUM_FILE: "{{.CHECKSUM_FILE}}"
          DATA_PATHS: ["{{.OUTPUT_DIR}}"]
    cmds:
      - |-
        rm -rf "{{.OUTPUT_DIR}}"
        mkdir -p "{{.OUTPUT_DIR}}"
        tar -x --strip-components="{{.STRIP}}" -C "{{.OUTPUT_DIR}}" -f "{{.TAR_FILE}}"
      # This command must be last
      - task: "utils:compute-checksum"
        vars:
          DATA_PATHS: ["{{.OUTPUT_DIR}}"]
          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"

  ## PR AND REMOVE

  utils:compute-checksum:
    desc: "Tries to compute a checksum for the given directory and output it to a file."
    internal: true
    silent: true
    requires:
      vars: ["DATA_PATHS", "OUTPUT_FILE"]
    cmds:
      - >-
        tar cf -
        --group 0
        --mtime "UTC 1970-01-01"
        --numeric-owner
        --owner 0
        --sort name
        {{- range .EXCLUDE_PATHS}}
        --exclude="{{.}}"
        {{- end}}
        {{- range .DATA_PATHS}}
        "{{.}}"
        {{- end}}
        2> /dev/null
        | md5sum > {{.OUTPUT_FILE}}
    # Ignore errors so that dependent tasks don't fail
    ignore_error: true

  # @param {[]string} [DATA_PATHS] A list of paths to validate the checksum for.
  # @param {string} OUTPUT_FILE
  # @param {[]string} [EXCLUDE_PATHS] A list of paths, relative to any `DATA_PATHS`, to exclude from
  # the checksum.
  utils:validate-checksum:
    desc: "Validates the checksum of the given directory matches the checksum in the given file, or
    deletes the checksum file otherwise."
    internal: true
    silent: true
    vars:
      TMP_CHECKSUM_FILE: "{{.CHECKSUM_FILE}}.tmp"
    requires:
      vars: ["CHECKSUM_FILE", "DATA_PATHS"]
    cmds:
      - task: "utils:compute-checksum"
        vars:
          DATA_PATHS:
            ref: ".DATA_PATHS"
          EXCLUDE_PATHS:
            ref: ".EXCLUDE_PATHS"
          OUTPUT_FILE: "{{.TMP_CHECKSUM_FILE}}"
      - defer: "rm -f '{{.TMP_CHECKSUM_FILE}}'"
      # Check that the directory exists and the checksum matches; otherwise delete the checksum file
      - >-
        (
        {{- range .DATA_PATHS}}
        test -e "{{.}}" &&
        {{- end}}
        diff -q '{{.TMP_CHECKSUM_FILE}}' '{{.CHECKSUM_FILE}}' 2> /dev/null
        ) || rm -f '{{.CHECKSUM_FILE}}'
