version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  bazel: "taskfiles/bazel.yaml"
  cpp: "taskfiles/cpp.yaml"
  deps: "taskfiles/deps.yaml"
  go: "taskfiles/go.yaml"
  lint: "taskfiles/lint.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_INSTALL_PREFIX: "{{.ROOT_DIR}}/pre-built"
  G_INSTALL_INCLUDE_DIR: "{{.G_INSTALL_PREFIX}}/include/clp-ffi-go"

  # NOTE: This path must be kept in-sync with its usage in CMakeLists.txt.
  G_INSTALL_LIB: >-
    {{printf "%s/lib/libclp-ffi-go_%s_%s.a" .G_INSTALL_PREFIX OS ARCH}}

tasks:
  build:
    deps:
      - "bazel:build"
      - "go:build"

  clean:
    deps:
      - "bazel:clean"
      - "cpp:clean-debug"
      - "cpp:clean-release"
      - "go:clean"
    cmd: "rm -fr {{.G_BUILD_DIR}}"

  test:
    deps:
      - "bazel:test"
      - "go:test"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
