// Code generated by "stringer -type=IrError"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[DecodeError-1]
	_ = x[EndOfIr-2]
	_ = x[CorruptedIr-3]
	_ = x[IncompleteIr-4]
	_ = x[QueryNotFound-5]
	_ = x[EncodeError-6]
	_ = x[UnsupportedVersion-7]
}

const _IrError_name = "SuccessDecodeErrorEndOfIrCorruptedIrIncompleteIrQueryNotFoundEncodeErrorUnsupportedVersion"

var _IrError_index = [...]uint8{0, 7, 18, 25, 36, 48, 61, 72, 90}

func (i IrError) String() string {
	if i < 0 || i >= IrError(len(_IrError_index)-1) {
		return "IrError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IrError_name[_IrError_index[i]:_IrError_index[i+1]]
}
