// Code generated by "stringer -type=MsgError"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DecodeError-1]
	_ = x[NilRef-2]
}

const _MsgError_name = "DecodeErrorNilRef"

var _MsgError_index = [...]uint8{0, 11, 17}

func (i MsgError) String() string {
	i -= 1
	if i < 0 || i >= MsgError(len(_MsgError_index)-1) {
		return "MsgError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MsgError_name[_MsgError_index[i]:_MsgError_index[i+1]]
}
